general:
  log_level: DEBUG
  default_timezone: America/Los_Angeles
bootstrap:
  host: broker
  port: 29092
schema_registry:
  host: schema-registry
  port: 8081
topics:
  input_topic: stream-tweets
  output_topic: stream-sentiment
