kafka:
  clusters:
    - name: practica
      bootstrapServers: http://broker:29092
      kafkaConnect: 
        clusters:
          - name: connect
            address: http://localhost:8083
      KSQLDBServer: http://ksqldb-server:8088
      schemaRegistry: http://schema-registry:8081